server:
  port: 8100

spring:
  application:
    name: jwt-auth-server-service

  redis:
    database: 0
    host: localhost
    port: 6379

eureka:
#  instance:
#    hostname: jwt-auth-server-service-8100

  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
